services:
    mysql:
        image: mysql:8.0
        tty: true
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            SERVICE_NAME: mysql
        container_name: TM_APP_DBSERVER
        volumes:
            - ./mysql/data:/var/lib/mysql
